---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydockertestdeploymentnew
  replicas: 2
  selector:
    matchLabels:
      app: mydockertestnew
  template:
    metadata:
      labels:
        app: mydockertestnew
    spec:
      containers:
        - name: mydockertestnew
          image: kkataria1983/scuticommerce:v1
          ports:
            - containerPort: 8080
